"""Baymax API composition and backwards-compatible public entry point."""

from __future__ import annotations

from fastapi import FastAPI

from .calculations import (
    budget_payload as _budget_payload,
    category_summary as _category_summary,
    cycle_bounds as _cycle_bounds,
    cycle_label as _cycle_label,
    cycle_start as _cycle_start,
    expenses_for_cycle as _expenses_for_cycle,
    goal_entries as _goal_entries,
    goal_summary as _goal_summary,
    known_category_names as _known_category_names,
    next_cycle_start as _next_cycle_start,
    report_payload as _report_payload,
)
from .intents import (
    BaymaxIntent,
    CorrectExpenseIntent,
    InterpretIntentRequest,
    LogExpenseIntent,
    QuerySpendingIntent,
    RemoveBudgetIntent,
    ReportIntent,
    SetBudgetIntent,
    ShowHistoryIntent,
    SuggestBudgetIntent,
    UnknownIntent,
    validate_intent,
)
from .models import (
    AskRequest,
    AskResponse,
    CreateExpenseRequest,
    ExpenseDraft,
    ParseExpenseRequest,
    SetBudgetRequest,
    UpdateExpenseRequest,
)
from .parsing import (
    canonical_goal_name as _canonical_goal_name,
    extract_amount as _extract_amount,
    extract_category as _extract_category,
    extract_description as _extract_description,
    extract_expense_details as _extract_expense_details,
    extract_flags as _extract_flags,
    goal_candidates as _goal_candidates,
    normalized_name as _normalized_name,
)
from .routes import (
    ask_question,
    create_expense,
    execute_language,
    get_budgets,
    get_expense_suggestions,
    get_goal_summary,
    get_reports,
    interpret_language,
    list_expenses,
    parse_expense,
    remove_budget,
    root,
    router,
    set_budget,
    update_expense,
)
from .rule_interpreter import interpret_intent
from .store import reset_database, reset_in_memory_store

__all__ = [
    "AskRequest",
    "AskResponse",
    "BaymaxIntent",
    "CorrectExpenseIntent",
    "CreateExpenseRequest",
    "ExpenseDraft",
    "InterpretIntentRequest",
    "LogExpenseIntent",
    "ParseExpenseRequest",
    "QuerySpendingIntent",
    "RemoveBudgetIntent",
    "ReportIntent",
    "SetBudgetIntent",
    "SetBudgetRequest",
    "ShowHistoryIntent",
    "SuggestBudgetIntent",
    "UnknownIntent",
    "UpdateExpenseRequest",
    "_budget_payload",
    "_canonical_goal_name",
    "_category_summary",
    "_cycle_bounds",
    "_cycle_label",
    "_cycle_start",
    "_expenses_for_cycle",
    "_extract_amount",
    "_extract_category",
    "_extract_description",
    "_extract_expense_details",
    "_extract_flags",
    "_goal_candidates",
    "_goal_entries",
    "_goal_summary",
    "_known_category_names",
    "_next_cycle_start",
    "_normalized_name",
    "_report_payload",
    "app",
    "ask_question",
    "create_expense",
    "execute_language",
    "get_budgets",
    "get_expense_suggestions",
    "get_goal_summary",
    "get_reports",
    "interpret_intent",
    "interpret_language",
    "list_expenses",
    "parse_expense",
    "remove_budget",
    "reset_database",
    "reset_in_memory_store",
    "root",
    "set_budget",
    "update_expense",
    "validate_intent",
]

app = FastAPI(
    title="Baymax API",
    version="0.1.0",
    description="SQLite-backed API for the Baymax expense-tracking prototype.",
)
app.include_router(router)
