from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal, Optional
from uuid import uuid4

from fastapi import APIRouter, HTTPException, Query

from .calculations import (
    budget_payload,
    category_summary,
    expenses_for_cycle,
    goal_summary,
    report_payload,
)
from .db import DEFAULT_HOUSEHOLD_ID, DEFAULT_USER_ID
from .models import (
    AskRequest,
    AskResponse,
    CreateExpenseRequest,
    ExpenseDraft,
    ParseExpenseRequest,
    SetBudgetRequest,
    UpdateExpenseRequest,
)
from .parsing import (
    canonical_goal_name,
    expense_suggestions,
    extract_amount,
    extract_flags,
    normalized_name,
    parse_expense_input,
)
from .repositories import (
    categories as category_repository,
    expenses as expense_repository,
)

router = APIRouter()


@router.get("/")
def root() -> dict:
    return {
        "service": "baymax-api",
        "status": "ok",
        "message": "SQLite-backed expense calculations are running.",
    }


@router.post("/expenses/parse", response_model=ExpenseDraft)
def parse_expense(payload: ParseExpenseRequest) -> ExpenseDraft:
    raw_text = payload.raw_text.strip()
    try:
        amount = extract_amount(raw_text)
        parsed = parse_expense_input(raw_text)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    flags = extract_flags(raw_text)
    return ExpenseDraft(
        amount=amount,
        description=parsed.description,
        merchant=parsed.merchant,
        category=parsed.category,
        goal=parsed.goal,
        flags=flags,
        budget_treatment="excluded" if "one-off" in flags else "included",
        goal_candidates=parsed.goal_candidates,
        explicit_fields=parsed.explicit_fields,
        field_sources=parsed.field_sources,
        notes="Prototype parse result generated by the API server.",
    )


@router.get("/expenses/suggestions")
def get_expense_suggestions(
    field: Literal["m", "merchant", "c", "category", "g", "goal"] = Query(...),
    q: str = Query(default=""),
    description: str = Query(default=""),
) -> dict:
    aliases = {"m": "merchant", "c": "category", "g": "goal"}
    canonical_field = aliases.get(field, field)
    return {
        "field": canonical_field,
        "query": q,
        "items": expense_suggestions(canonical_field, q, description),
    }


@router.post("/expenses")
def create_expense(payload: CreateExpenseRequest) -> dict:
    category = normalized_name(payload.category) if payload.category else None
    flags = [normalized_name(flag) for flag in payload.flags]
    expense = {
        "id": f"exp-{uuid4().hex[:8]}",
        "household_id": DEFAULT_HOUSEHOLD_ID,
        "user_id": payload.user_id or DEFAULT_USER_ID,
        "amount": payload.amount,
        "description": payload.description,
        "merchant": payload.merchant,
        "category": category,
        "flags": flags,
        "budget_treatment": (
            "excluded" if "one-off" in flags else payload.budget_treatment
        ),
        "goals": [canonical_goal_name(goal) for goal in payload.goals],
        "notes": payload.notes,
        "date": str(payload.date or datetime.now(timezone.utc).date()),
    }
    return expense_repository.create(expense)


@router.patch("/expenses/{expense_id}")
def update_expense(expense_id: str, payload: UpdateExpenseRequest) -> dict:
    updates = payload.model_dump(exclude_unset=True)
    if "date" in updates and updates["date"] is not None:
        updates["date"] = str(updates["date"])
    if "category" in updates and updates["category"] is not None:
        updates["category"] = normalized_name(updates["category"])
    if "flags" in updates and updates["flags"] is not None:
        updates["flags"] = [normalized_name(flag) for flag in updates["flags"]]
        if "budget_treatment" not in updates:
            updates["budget_treatment"] = "excluded" if "one-off" in updates["flags"] else "included"
    if "goals" in updates and updates["goals"] is not None:
        updates["goals"] = [canonical_goal_name(goal) for goal in updates["goals"]]
    expense = expense_repository.update(expense_id, updates)
    if expense is None:
        raise HTTPException(status_code=404, detail="Expense not found")
    return expense


@router.get("/expenses")
def list_expenses(
    cycle: str = Query(default="current"),
    category: Optional[str] = Query(default=None),
) -> dict:
    expenses = expenses_for_cycle(cycle)
    if category:
        normalized_category = normalized_name(category)
        expenses = [
            expense
            for expense in expenses
            if expense.get("category") and normalized_name(expense["category"]) == normalized_category
        ]
    return {"cycle": cycle, "count": len(expenses), "items": expenses}


@router.get("/budgets")
def get_budgets(cycle: str = Query(default="current")) -> dict:
    return budget_payload(cycle)


@router.put("/budgets/{category_name}")
def set_budget(category_name: str, payload: SetBudgetRequest) -> dict:
    normalized = normalized_name(category_name)
    existing = category_repository.get(normalized)
    if existing is None:
        category_repository.set_budget(normalized, payload.amount)
        action = "created"
        previous_budget = None
    else:
        previous_budget = existing["budget_amount"]
        action = "set" if previous_budget is None or previous_budget == payload.amount else "updated"
        category_repository.set_budget(normalized, payload.amount)

    category = category_summary(normalized, expenses_for_cycle("current"))
    return {"action": action, "category": category, "previous_budget": previous_budget}


@router.delete("/budgets/{category_name}")
def remove_budget(category_name: str) -> dict:
    normalized = normalized_name(category_name)
    existing = category_repository.get(normalized)
    if existing is None:
        return {"action": "missing", "category_name": normalized}

    previous_budget = existing["budget_amount"]
    category = category_summary(normalized, expenses_for_cycle("current"))
    if previous_budget is None:
        return {"action": "already_removed", "category": category}

    category_repository.set_budget(normalized, None)
    category = category_summary(normalized, expenses_for_cycle("current"))
    return {"action": "removed", "category": category, "previous_budget": previous_budget}


@router.get("/goals/{goal_id}/summary")
def get_goal_summary(goal_id: str, cycle: str = Query(default="current")) -> dict:
    return goal_summary(goal_id, cycle)


@router.post("/ask", response_model=AskResponse)
def ask_question(payload: AskRequest) -> AskResponse:
    question = payload.question.strip()
    lowered = question.lower()
    budgets = budget_payload(payload.cycle)

    if lowered == "how much on groceries this cycle?":
        groceries = next(
            (category for category in budgets["categories"] if category["name"] == "groceries"),
            None,
        )
        if groceries is None:
            raise HTTPException(status_code=404, detail="Groceries category not found")
        budget_amount = groceries["budget_amount"]
        spent = float(groceries["spent"])
        count = int(groceries["expense_count"])
        if budget_amount is None:
            answer = f"Groceries: ${spent:.2f} — {count} expenses"
        else:
            percent = round((spent / float(budget_amount)) * 100) if budget_amount else 0
            answer = f"Groceries: ${spent:.2f} of ${float(budget_amount):.2f} ({percent}%) — {count} expenses"
        return AskResponse(
            answer=answer,
            cycle=payload.cycle,
            supporting_data={
                "question": question,
                "category": "groceries",
                "spent": spent,
                "budget_amount": budget_amount,
                "expense_count": count,
            },
        )

    goal_questions = {
        "what did we put toward the resilient kid goal this cycle?",
        "what did we spend supporting the resilient kid goal this cycle?",
    }
    if lowered in goal_questions:
        goal = goal_summary("goal-resilient-kid", payload.cycle)
        details = ", ".join(
            f"{entry['description']} ${float(entry['amount']):.0f}"
            for entry in goal["cycle_entries"]
        )
        answer = (
            f"${float(goal['cycle_goal_related_spending']):.2f} of goal-related spending across "
            f"{int(goal['cycle_expense_count'])} expenses"
        )
        if details:
            answer += f" — {details}"
        return AskResponse(
            answer=answer,
            cycle=payload.cycle,
            supporting_data={
                "question": question,
                "goal_id": goal["id"],
                "goal_name": goal["name"],
                "cycle_goal_related_spending": goal["cycle_goal_related_spending"],
                "cycle_entries": goal["cycle_entries"],
            },
        )

    totals = budgets["totals"]
    return AskResponse(
        answer=(
            f"You have spent ${float(totals['spent']):.2f} across budgeted categories this cycle, "
            f"with ${float(totals['remaining']):.2f} remaining."
        ),
        cycle=payload.cycle,
        supporting_data={
            "question": question,
            "budget_totals": totals,
            "top_category": "groceries",
        },
    )


@router.get("/reports")
def get_reports(
    type: Literal["category", "goal", "flag"] = Query(default="category"),
    cycle: str = Query(default="current"),
) -> dict:
    return report_payload(type, cycle)
