from __future__ import annotations

from copy import deepcopy
from datetime import datetime, timezone
from typing import Literal, Optional
from uuid import uuid4

from fastapi import APIRouter, HTTPException, Query

from .calculations import (
    budget_payload,
    category_summary,
    expenses_for_cycle,
    goal_summary,
    report_payload,
)
from .models import (
    AskRequest,
    AskResponse,
    CreateExpenseRequest,
    ExpenseDraft,
    ParseExpenseRequest,
    SetBudgetRequest,
    UpdateExpenseRequest,
)
from .parsing import (
    canonical_goal_name,
    extract_amount,
    extract_category,
    extract_description,
    extract_flags,
    goal_candidates,
    normalized_name,
)
from .store import CATEGORY_BUDGETS, EXPENSES

router = APIRouter()


@router.get("/")
def root() -> dict:
    return {
        "service": "baymax-api",
        "status": "ok",
        "message": "In-memory expense calculations are running.",
    }


@router.post("/expenses/parse", response_model=ExpenseDraft)
def parse_expense(payload: ParseExpenseRequest) -> ExpenseDraft:
    raw_text = payload.raw_text.strip()
    description = extract_description(raw_text)
    return ExpenseDraft(
        amount=extract_amount(raw_text),
        description=description,
        category=extract_category(description),
        flags=extract_flags(raw_text),
        goal_candidates=goal_candidates(raw_text),
        notes="Prototype parse result generated by the API server.",
    )


@router.post("/expenses")
def create_expense(payload: CreateExpenseRequest) -> dict:
    category = normalized_name(payload.category) if payload.category else None
    if category and category not in CATEGORY_BUDGETS:
        CATEGORY_BUDGETS[category] = None

    expense = {
        "id": f"exp-{uuid4().hex[:8]}",
        "household_id": "household-1",
        "user_id": payload.user_id or "user-1",
        "amount": payload.amount,
        "description": payload.description,
        "category": category,
        "flags": [normalized_name(flag) for flag in payload.flags],
        "goals": [canonical_goal_name(goal) for goal in payload.goals],
        "notes": payload.notes,
        "date": str(payload.date or datetime.now(timezone.utc).date()),
    }
    EXPENSES.append(expense)
    return deepcopy(expense)


@router.patch("/expenses/{expense_id}")
def update_expense(expense_id: str, payload: UpdateExpenseRequest) -> dict:
    for expense in EXPENSES:
        if expense["id"] != expense_id:
            continue

        updates = payload.model_dump(exclude_unset=True)
        if "date" in updates and updates["date"] is not None:
            updates["date"] = str(updates["date"])
        if "category" in updates and updates["category"] is not None:
            updates["category"] = normalized_name(updates["category"])
            CATEGORY_BUDGETS.setdefault(updates["category"], None)
        if "flags" in updates and updates["flags"] is not None:
            updates["flags"] = [normalized_name(flag) for flag in updates["flags"]]
        if "goals" in updates and updates["goals"] is not None:
            updates["goals"] = [canonical_goal_name(goal) for goal in updates["goals"]]
        expense.update(updates)
        return deepcopy(expense)
    raise HTTPException(status_code=404, detail="Expense not found")


@router.get("/expenses")
def list_expenses(
    cycle: str = Query(default="current"),
    category: Optional[str] = Query(default=None),
) -> dict:
    expenses = expenses_for_cycle(cycle)
    if category:
        normalized_category = normalized_name(category)
        expenses = [
            expense
            for expense in expenses
            if expense.get("category") and normalized_name(expense["category"]) == normalized_category
        ]
    return {"cycle": cycle, "count": len(expenses), "items": deepcopy(expenses)}


@router.get("/budgets")
def get_budgets(cycle: str = Query(default="current")) -> dict:
    return budget_payload(cycle)


@router.put("/budgets/{category_name}")
def set_budget(category_name: str, payload: SetBudgetRequest) -> dict:
    normalized = normalized_name(category_name)
    if normalized not in CATEGORY_BUDGETS:
        CATEGORY_BUDGETS[normalized] = payload.amount
        action = "created"
        previous_budget = None
    else:
        previous_budget = CATEGORY_BUDGETS[normalized]
        action = "set" if previous_budget is None or previous_budget == payload.amount else "updated"
        CATEGORY_BUDGETS[normalized] = payload.amount

    category = category_summary(normalized, expenses_for_cycle("current"))
    return {"action": action, "category": category, "previous_budget": previous_budget}


@router.delete("/budgets/{category_name}")
def remove_budget(category_name: str) -> dict:
    normalized = normalized_name(category_name)
    if normalized not in CATEGORY_BUDGETS:
        return {"action": "missing", "category_name": normalized}

    previous_budget = CATEGORY_BUDGETS[normalized]
    category = category_summary(normalized, expenses_for_cycle("current"))
    if previous_budget is None:
        return {"action": "already_removed", "category": category}

    CATEGORY_BUDGETS[normalized] = None
    category = category_summary(normalized, expenses_for_cycle("current"))
    return {"action": "removed", "category": category, "previous_budget": previous_budget}


@router.get("/goals/{goal_id}/summary")
def get_goal_summary(goal_id: str, cycle: str = Query(default="current")) -> dict:
    return goal_summary(goal_id, cycle)


@router.post("/ask", response_model=AskResponse)
def ask_question(payload: AskRequest) -> AskResponse:
    question = payload.question.strip()
    lowered = question.lower()
    budgets = budget_payload(payload.cycle)

    if lowered == "how much on groceries this cycle?":
        groceries = next(
            (category for category in budgets["categories"] if category["name"] == "groceries"),
            None,
        )
        if groceries is None:
            raise HTTPException(status_code=404, detail="Groceries category not found")
        budget_amount = groceries["budget_amount"]
        spent = float(groceries["spent"])
        count = int(groceries["expense_count"])
        if budget_amount is None:
            answer = f"Groceries: ${spent:.2f} — {count} expenses"
        else:
            percent = round((spent / float(budget_amount)) * 100) if budget_amount else 0
            answer = f"Groceries: ${spent:.2f} of ${float(budget_amount):.2f} ({percent}%) — {count} expenses"
        return AskResponse(
            answer=answer,
            cycle=payload.cycle,
            supporting_data={
                "question": question,
                "category": "groceries",
                "spent": spent,
                "budget_amount": budget_amount,
                "expense_count": count,
            },
        )

    if lowered == "what did we put toward the resilient kid goal this cycle?":
        goal = goal_summary("goal-resilient-kid", payload.cycle)
        details = ", ".join(
            f"{entry['description']} ${float(entry['amount']):.0f}"
            for entry in goal["cycle_entries"]
        )
        answer = (
            f"${float(goal['cycle_contributions']):.2f} across "
            f"{int(goal['cycle_expense_count'])} expenses"
        )
        if details:
            answer += f" — {details}"
        return AskResponse(
            answer=answer,
            cycle=payload.cycle,
            supporting_data={
                "question": question,
                "goal_id": goal["id"],
                "goal_name": goal["name"],
                "cycle_contributions": goal["cycle_contributions"],
                "cycle_entries": goal["cycle_entries"],
            },
        )

    totals = budgets["totals"]
    return AskResponse(
        answer=(
            f"You have spent ${float(totals['spent']):.2f} across budgeted categories this cycle, "
            f"with ${float(totals['remaining']):.2f} remaining."
        ),
        cycle=payload.cycle,
        supporting_data={
            "question": question,
            "budget_totals": totals,
            "top_category": "groceries",
        },
    )


@router.get("/reports")
def get_reports(
    type: Literal["category", "goal", "flag"] = Query(default="category"),
    cycle: str = Query(default="current"),
) -> dict:
    return report_payload(type, cycle)
